export const BRAVE_MISSIONS = [
  {
    day: 1,
    frameworkTag: 'FEARLESS',
    difficulty: 1,
    title: 'The 3-Second Scan',
    description: 'No conversations today. Just observation. Pick three people in public and read their body language for 3 seconds each. Green light or red light? You are training your eyes, not your mouth.',
    variants: {
      invisible: 'You spend most of your life avoiding eye contact. Today, you look. You do not approach. You just see. That is enough.',
      performer: 'Stop watching how you look to others. Watch them instead. Notice who looks open, who looks closed. This is data, not judgment.',
      frozen: 'You usually skip step one and go straight to overthinking. Today, no thinking. Just scan. Read three bodies and move on. No pressure to do anything with what you see.',
      competent: 'You already do this intuitively. Today, do it consciously. Catch yourself making the read. Notice what cues you actually use.',
    },
    shavonNote: 'Most guys try to talk before they learn to see. That is why their approaches feel random. Today you learn the read. Tomorrow you use it.',
  },
  {
    day: 2,
    frameworkTag: 'FEARLESS',
    difficulty: 1,
    title: 'The Barista Method',
    description: 'One low-stakes interaction today. A barista, a cashier, anyone whose job involves talking to you. Go past "thanks." Say one extra sentence. Ask one small question. Make it light. Make it short.',
    variants: {
      invisible: 'Even one extra sentence is huge for you. "How is your shift going?" That is the whole mission. You do not have to be witty.',
      performer: 'Drop the charm. Drop the performance. Just be a normal guy having a normal small exchange. Boring is the goal today.',
      frozen: 'The script is already there. They will respond. You do not have to plan anything past one sentence. Just open your mouth.',
      competent: 'Pay attention to their face when you go past "thanks." Most people light up. That signal is data you can use everywhere else.',
    },
    shavonNote: 'The barista method works because they are already going to talk to you. You are not approaching. You are extending what is already happening. Lowest stakes possible.',
  },
  {
    day: 3,
    frameworkTag: 'TALK',
    difficulty: 2,
    title: 'TALK Check Yourself',
    description: 'Pick one real conversation today. Family, coworker, friend, anyone. While it is happening, silently track four things in yourself. Tone (is your voice flat or alive?). Attention (are you actually listening or rehearsing your reply?). Language (clear or rambling?). Kinetics (are you fidgeting, frozen, or grounded?). No fixing. Just noticing.',
    variants: {
      invisible: 'You probably already monitor yourself in conversations. Today, monitor differently. Not "do they like me?" but "where is my body right now?"',
      performer: 'This one is going to feel uncomfortable. You are going to notice how much of your tone is performance. Notice it. Do not fight it yet.',
      frozen: 'You freeze because you are running too many programs at once. TALK Check forces one program to the foreground. It actually slows the freeze down.',
      competent: 'You are going to catch yourself doing small things wrong. Good. That is the gap between what you think you do and what you actually do.',
    },
    shavonNote: 'You cannot fix what you cannot see. Today is the X-ray. The treatment comes later.',
  },
  {
    day: 4,
    frameworkTag: 'FEARLESS',
    difficulty: 2,
    title: 'The 3-2-1 Method',
    description: 'One real approach today. Pick someone who passed your scan. Count down in your head: 3, 2, 1. Walk over. Use one Universal Opener: an observation about the moment, a small question, or a shared-experience comment. Talk for 30 seconds. Exit cleanly.',
    variants: {
      invisible: 'You will want to wait for the perfect moment. There is no perfect moment. Count down and go. Your body will follow.',
      performer: 'Do not pre-script anything clever. Just walk and say what is true. The point is the move, not the line.',
      frozen: 'This entire method exists for you. The countdown is the override. Your brain does not get to vote. The body moves at zero.',
      competent: 'You can already approach. Today, watch how fast you go from decision to action. Speed reveals how trained your nervous system is.',
    },
    shavonNote: 'The 3-2-1 is the single most useful tool I built into this whole system. Action before doubt. Every time.',
  },
  {
    day: 5,
    frameworkTag: 'SPARK',
    difficulty: 2,
    title: 'Run the SPARK Sequence',
    description: 'One conversation today, structured. S: Start with an observation or question. P: Personalize with one small detail about them or the moment. A: Ask one open question. R: Respond to what they actually said, not what you planned. K: Keep it brief and exit on a high note.',
    variants: {
      invisible: 'The structure is your safety net. You do not have to improvise. Every letter tells you what to do next.',
      performer: 'SPARK forces you off your usual rotation of stories. You have to actually respond to them. Stay with their thread.',
      frozen: 'You will want to think through all five steps before you start. Do not. Just start at S. The rest builds itself.',
      competent: 'You probably do most of SPARK already by feel. Today, do it on purpose. Notice which letter you skip.',
    },
    shavonNote: 'SPARK is what you do AFTER you approach. The 3-2-1 gets you there. SPARK keeps you alive once you arrive.',
  },
  {
    day: 6,
    frameworkTag: 'TALK',
    difficulty: 3,
    title: 'Go Deeper with FORD',
    description: 'Take one conversation past small talk today. Use the FORD method: Family, Occupation, Recreation, or Dreams. Pick the angle that feels most natural. Ask one real question in that category. Listen for two minutes without interrupting. Then ask one follow-up.',
    variants: {
      invisible: 'The dreams angle is yours. "What is something you are working toward?" Most people light up. They never get asked.',
      performer: 'You usually steer conversations to topics that make you look good. FORD steers them toward THEM. Stay there.',
      frozen: 'You can prepare one FORD question in advance. That is allowed. The point is using it, not generating it on the fly.',
      competent: 'You can do FORD without thinking. Today, pick the category you usually avoid. If you always ask about work, ask about dreams. If you always ask about hobbies, ask about family.',
    },
    shavonNote: 'Surface conversations are why people feel lonely after social events. FORD is how you actually get to know someone in five minutes.',
  },
  {
    day: 7,
    frameworkTag: 'FEARLESS',
    difficulty: 3,
    title: 'Full Integration',
    description: 'Today you run the whole system in one moment. Scan a room. Pick someone with green lights. 3-2-1 approach. Open with SPARK. TALK Check yourself mid-conversation. Use FORD to go one layer deeper. Exit cleanly. Optional: get their contact if it feels natural. This is the day the whole system becomes one move.',
    variants: {
      invisible: 'Seven days ago you would not have considered this possible. The fact that you are at Day 7 already proves the point. Now do the thing.',
      performer: 'No charm offensive today. Run the system clean. Boring execution wins.',
      frozen: 'You have already done every piece of this in isolation. Today you just connect them. Your brain will try to convince you the integration is harder than the parts. It is not.',
      competent: 'Today is the audit. Do you actually have the skills you think you have? Run the full sequence and find out.',
    },
    shavonNote: 'Day 7 is not the end. It is the moment you become someone who can do this on purpose. What comes next is making it automatic.',
  },
];